cloud: aws
category:
  - self-hosted
infra: eks
stack:
  - terraform
  - helm
  - manifest
features:
  - actions
  - policies
  - secrets
tags:
  - eks
  - kubernetes
  - design
  - postgresql
links:
  upstream: https://penpot.app
