image: {{ .nuon.components.img_forgejo.outputs.image.repository }}:{{ .nuon.components.img_forgejo.outputs.image.tag }}
replicas: 1

adminUser:  {{ .nuon.inputs.inputs.forgejo_admin_user }}
adminEmail: {{ .nuon.inputs.inputs.forgejo_admin_email }}

siteDomain: {{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}

repoStorageGB: {{ .nuon.inputs.inputs.repo_storage_gb }}
repoStorageClass: gp2
