# terraform
name              = "rds_cluster_sonar"
type              = "terraform_module"
terraform_version = "1.13.5"
dependencies      = ["rds_subnet"]
max_auto_retries = 5
skip_noops        = true

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "sonar/sonar-aws/src/components/rds_cluster_sonar"
branch    = "mm/sonar"

[vars]
identifier      = "sonar-{{ .nuon.install.id }}"
port            = "5432"
db_name         = "sonar"
db_user         = "sonar"
instance_class  = "{{ .nuon.install.inputs.sonar_db_instance_type }}"
subnet_group_id = "{{ .nuon.components.rds_subnet.outputs.id }}"

region     = "{{ .nuon.install_stack.outputs.region }}"
vpc_id     = "{{ .nuon.install_stack.outputs.vpc_id }}"
subnet_ids = '{{ .nuon.sandbox.outputs.vpc.private_subnet_ids | join "," }}'

nuon_id = "{{ .nuon.install.id }}"

iam_database_authentication_enabled = "false"
deletion_protection                 = "false"
skip_final_snapshot                 = "true"
storage_encrypted                   = "true"

allocated_storage = "50"
apply_immediately = "true"
