# helm
name             = "whoami_qa"
type             = "helm_chart"
chart_name       = "whoami-qa"
namespace        = "qa"
storage_driver   = "configmap"
max_auto_retries = 5

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "eks-multi-env/src/components/whoami"
branch    = "main"

[[values_file]]
contents = "./values/whoami.yaml"
