#:schema http://localhost:8081/v1/general/config-schema/app-branch

name = "main"

[public_repo]
repo = "https://github.com/RealHarshThakur/example-app-configs.git"
directory = "event-automation-minimal"
branch = "ht/http-app-branch"
