install_name: ""
namespace: ""
domain: ""
cert_map: ""

coder_service: "coder"
coder_namespace: "coder"
coder_port: "80"

grafana_service: "grafana"
grafana_namespace: "coder-observability"
grafana_port: "80"
