[[role]]
name           = "{{.nuon.install.id}}-gke-wi-break-glass"
description    = "Emergency access role for install {{.nuon.install.id}}. Grants broad GCP access but excludes Secret Manager admin."
display_name   = "break glass role"
cloud_platform = "gcp"

[[role.policies]]
name                = "editor"
gcp_predefined_role = "roles/editor"
