[[policy]]
type = "kubernetes_cluster"
contents = "./policies/disallow-ingress-nginx-custom-snippets.yml"

[[policy]]
type     = "sandbox"
engine   = "opa"
contents = "./policies/pass-vpc-cidr.rego"

[[policy]]
type     = "sandbox"
engine   = "opa"
contents = "./policies/pass-multi-az-subnets.rego"
