[[role]]
name = "{{.nuon.install.id}}-aws-lambda-break-glass-permission"
description = "{{.nuon.install.id}} grant elevated permissions"
display_name = "AWS Lambda: Break Glass for Install {{.nuon.install.id}}"
permissions_boundary = ""

[[role.policies]]
managed_policy_name = "AdministratorAccess"

[[role.policies]]
name = "{{.nuon.install.id}}-bg-remove-secrets-manager"
contents = """
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DenySecretsManagerAccess",
            "Effect": "Deny",
            "Action": [
                "secretsmanager:*"
            ],
            "Resource": "*"
        }
    ]
}
"""
