#:schema https://api.nuon.co/v1/general/config-schema?type=kubernetes-manifest

name = "default_storage_class"
type = "kubernetes_manifest"
dependencies = []

namespace = "baserow"
manifest = """
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
"""