#:schema https://api.nuon.co/v1/general/config-schema?type=helm
name           = "baserow"
type           = "helm_chart"
chart_name     = "baserow"
namespace      = "baserow"
storage_driver = "configmap"
<<<<<<< HEAD
dependencies   = ["default_storage_class", "baserow_s3_bucket"]
=======
dependencies   = ["default_storage_class"]
>>>>>>> 9cdff126dc5c1feb8a6d6e5deaf61b440d3ea1f0

[public_repo]
repo      = "christianhuth/helm-charts"
directory = "charts/baserow"
<<<<<<< HEAD
branch    = "mm/baserow"
=======
branch    = "main"
>>>>>>> 9cdff126dc5c1feb8a6d6e5deaf61b440d3ea1f0

[[values_file]]
contents = "./values/baserow/values.yaml"
