#:schema https://api.nuon.co/v1/general/config-schema?type=helm
name           = "baserow"
type           = "helm_chart"
chart_name     = "baserow"
namespace      = "baserow"
storage_driver = "configmap"
dependencies   = ["default_storage_class"]

[public_repo]
# commenting out christianhuth repo to override
# healthcheck path
#repo      = "christianhuth/helm-charts"
#directory = "charts/baserow"
repo      = "nuonco/example-app-configs"
directory = "baserow/src/helm/baserow"
branch    = "mm/baserow"

[[values_file]]
contents = "./values/baserow/values.yaml"
