[[group]]
name         = "storage"
description  = "Storage configuration"
display_name = "Storage"

[[input]]
name         = "blob_versioning"
description  = "Enable blob versioning on the customer-created storage account."
default      = "false"
display_name = "Blob Versioning"
group        = "storage"
type         = "bool"
