# action
name    = "ingress_status"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name    = "status"
inline_contents = """
#!/usr/bin/env sh

set -e
set -o pipefail
set -u

echo "=== Ingress ==="
kubectl get ingress -n whoami

echo ""
echo "=== Ingress Details ==="
kubectl describe ingress -n whoami

# json for outputs
response=`kubectl get ingress -n whoami -o json | jq -c`
echo $response >> $NUON_ACTIONS_OUTPUT_FILEPATH
"""
