terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/azure-min-sandbox"
directory = "."
branch    = "main"

[vars]
nuon_id              = "{{.nuon.install.id}}"
location             = "{{.nuon.cloud_account.azure.location}}"
resource_group_name  = "{{.nuon.install_stack.outputs.resource_group_name}}"
vnet_name            = "{{.nuon.install_stack.outputs.network_name}}"
private_subnet_names = "{{.nuon.install_stack.outputs.private_subnet_names}}"
public_subnet_names  = "{{.nuon.install_stack.outputs.public_subnet_names}}"
enable_nuon_dns      = "false"

[[var_file]]
contents = "./sandbox.tfvars"
