name              = "certificate"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "aks-simple/src/components/certificate"
branch    = "ht/azure"

[vars]
install_id        = "{{ .nuon.install.id }}"
resource_group    = "{{ .nuon.install_stack.outputs.resource_group_name }}"
subscription_id   = "{{ .nuon.install_stack.outputs.subscription_id }}"
dns_zone_name     = "{{ .nuon.install.sandbox.outputs.public_domain.name }}"
dns_zone_id       = "{{ .nuon.install.sandbox.outputs.public_domain.id }}"
oidc_issuer_url   = "{{ .nuon.install.sandbox.outputs.cluster.oidc_issuer_url }}"
domain_name       = "{{ .nuon.inputs.inputs.sub_domain }}.{{ .nuon.install.sandbox.outputs.public_domain.name }}"
