#:schema https://api.nuon.co/v1/general/config-schema?type=helm

name         = "cert_manager_issuer"
type         = "helm_chart"
chart_name   = "cert-manager-issuer"
namespace    = "cert-manager"
dependencies = ["cert_manager"]
max_auto_retries = 5

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "aks-simple/src/components/cert_manager_issuer"
branch    = "main"

[values]
email = "noreply@nuon.co"
