#:schema https://api.nuon.co/v1/general/config-schema?type=helm

name         = "external_dns"
type         = "helm_chart"
chart_name   = "external-dns"
namespace    = "external-dns"
dependencies = ["nginx_ingress_controller"]

[connected_repo]
repo      = "nuonco/aks-simple"
directory = "src/components/external_dns"
branch    = "main"

[values]
"external-dns.azure.resourceGroup"  = "{{.nuon.install_stack.outputs.resource_group_name}}"
"external-dns.azure.tenantId"       = "{{.nuon.install_stack.outputs.subscription_tenant_id}}"
"external-dns.azure.subscriptionId" = "{{.nuon.install_stack.outputs.subscription_id}}"
"external-dns.domainFilters[0]"     = "{{.nuon.install.sandbox.outputs.public_domain.name}}"
"external-dns.txtOwnerId"           = "{{.nuon.install.id}}"
