#:schema https://api.nuon.co/v1/general/config-schema?source=helm
name           = "httpbin_helm_chart"
type           = "helm_chart"
chart_name     = "httpbin"
namespace      = "{{.nuon.install.id}}"
storage_driver = "configmap"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "aks-simple/src/components/httpbin_helm_chart"
branch    = "ja/pro-1515-https-cert-component"

[[values_file]]
contents = "./values/httpbin.yaml"
