#:schema https://api.nuon.co/v1/general/config-schema?source=terraform_module

name           = "storage"
type           = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "aks-simple/src/components/storage"
branch    = "ja/pro-1515-https-cert-component"

[vars]
name = "jalocalazureaks022"
resource_group_name = "{{.nuon.install_stack.outputs.resource_group_name}}"
