# kubernetes-manifest
name         = "tailscale_proxy"
type         = "kubernetes_manifest"
namespace    = "tailscale"
manifest     = "./manifests/tailscale_proxy.yaml"
dependencies = ["crd_tailscale_operator"]
