apiVersion: v1
kind: Secret
metadata:
  name: forgejo-internal
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  LFS_JWT_SECRET: {{ randAlphaNum 43 | quote }}
  SECURITY_SECRET_KEY: {{ randAlphaNum 64 | quote }}
  INTERNAL_TOKEN: {{ randAlphaNum 105 | quote }}
