apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: forgejo
  {{- if .Values.serviceAccountRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountRoleArn | quote }}
  {{- end }}
