# terraform - Cloud SQL Postgres instance for Coder

name              = "cloudsql_coder"
type              = "terraform_module"
terraform_version = "1.11.3"
dependencies      = ["cloudsql_network"]

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "coder-gcp/src/components/cloudsql_coder"
branch    = "main"

[vars]
install_id          = "{{ .nuon.install.id }}"
project_id          = "{{ .nuon.install_stack.outputs.project_id }}"
region              = "{{ .nuon.install_stack.outputs.region }}"
network_self_link   = "{{ .nuon.components.cloudsql_network.outputs.network_self_link }}"
tier                = "{{ .nuon.install.inputs.coder_db_instance_tier }}"
db_name             = "coder"
db_user             = "coder"
deletion_protection = "false"
