image: code.forgejo.org/forgejo/forgejo:15.0.2
imagePullPolicy: IfNotPresent

replicas: 1

adminUser: forgejo-admin
adminEmail: admin@example.com

siteDomain: forgejo.example.com

repoStorageGB: 50
repoStorageClass: standard-rwo

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

dbSecretName: forgejo-db
cacheSecretName: forgejo-cache
