name               = "backend_secret"
timeout            = "2m"
enable_kube_config = true

[[triggers]]
type           = "post-deploy-component"
component_name = "materialize_operator"

[[triggers]]
type = "manual"

[[steps]]
name    = "Create Materialize backend secret"
command = "./create.sh"

[steps.public_repo]
repo      = "nuonco/example-app-configs"
directory = "materialize/src/actions/backend_secret"
branch    = "mm/materialize"

[steps.env_vars]
SECRET_ARN       = "{{ .nuon.components.rds_materialize.outputs.db_instance_master_user_secret_arn }}"
REGION           = "{{ .nuon.install_stack.outputs.region }}"
DB_ADDRESS       = "{{ .nuon.components.rds_materialize.outputs.address }}"
DB_PORT          = "{{ .nuon.components.rds_materialize.outputs.db_instance_port }}"
DB_NAME          = "{{ .nuon.components.rds_materialize.outputs.db_instance_name }}"
BUCKET_NAME      = "{{ .nuon.components.s3_persist.outputs.bucket_name }}"
PERSIST_PREFIX   = "{{ .nuon.components.s3_persist.outputs.persist_prefix }}"
TARGET_NAMESPACE = "materialize-environment"
TARGET_NAME      = "materialize-backend"
LICENSE_SECRET   = "materialize-license"
LICENSE_KEY_NAME = "license_key"
