name               = "mz_system_password"
timeout            = "1m"
enable_kube_config = true

[[triggers]]
type = "manual"

[[steps]]
name    = "Print mz_system password and connection info"
command = "./print.sh"

[steps.public_repo]
repo      = "nuonco/example-app-configs"
directory = "materialize/src/actions/mz_system_password"
branch    = "mm/materialize"

[steps.env_vars]
TARGET_NAMESPACE = "materialize-environment"
TARGET_NAME      = "materialize-backend"
CONSOLE_URL      = "https://{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"
SQL_HOST         = "sql.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"
