#:schema https://api.nuon.co/v1/general/config-schema?type=kubernetes-manifest

name   = "postgres_secrets" 
type   = "kubernetes_manifest"
dependencies   = ["grafana_postgres", "exampledb_postgres"]

namespace = "grafana"
manifest = """
# Secret for Grafana's internal database connection
apiVersion: v1
kind: Secret
metadata:
  name: grafana-postgres-secret
  namespace: grafana
type: Opaque
stringData:
  GF_DATABASE_URL: "postgres://grafana:grafana@postgresql.grafana.svc.cluster.local:5432/grafana?sslmode=disable&connect_timeout=10"
---
# Secret for ExampleDB datasource connection (stored in grafana namespace for Grafana to access)
apiVersion: v1
kind: Secret
metadata:
  name: exampledb-datasource-secret
  namespace: grafana
type: Opaque
stringData:
  DATASOURCE_URL: "postgres://exampledb:exampledb@postgresql.exampledb.svc.cluster.local:5432/exampledb?sslmode=disable&connect_timeout=10"
  DATASOURCE_PASSWORD: "exampledb"
"""