[[group]]
name         = "test"
description  = "Launch-test values"
display_name = "Test"

[[input]]
name         = "echo_value"
description  = "Value returned by the custom CloudFormation stack."
default      = "example-value"
display_name = "Echo value"
group        = "test"
