name             = "pulumi_s3"
type             = "pulumi"
runtime          = "go"
max_auto_retries = 5

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "forgejo-aws/src/components/pulumi-s3"
branch    = "main"

[config]
"aws:region" = "{{ .nuon.install_stack.outputs.region }}"

[env_vars]
INSTALL_ID            = "{{ .nuon.install.id }}"
CLUSTER_OIDC_PROVIDER = "{{ .nuon.install.sandbox.outputs.cluster.oidc_provider }}"
NAMESPACE             = "forgejo"
SERVICE_ACCOUNT       = "forgejo"
