name         = "forgejo_db_secret"
type         = "kubernetes_manifest"
dependencies = ["pulumi_rds"]
namespace    = "forgejo"

manifest = """
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-db
  namespace: forgejo
type: Opaque
stringData:
  host: "{{ .nuon.components.pulumi_rds.outputs.host }}"
  port: "{{ .nuon.components.pulumi_rds.outputs.port }}"
  database: "{{ .nuon.components.pulumi_rds.outputs.database }}"
  username: "{{ .nuon.components.pulumi_rds.outputs.username }}"
  password: "{{ .nuon.components.pulumi_rds.outputs.password }}"
"""
max_auto_retries = 5
