name         = "forgejo_s3_secret"
type         = "kubernetes_manifest"
dependencies = ["pulumi_s3"]
namespace    = "forgejo"

manifest = """
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-s3
  namespace: forgejo
type: Opaque
stringData:
  bucket: "{{ .nuon.components.pulumi_s3.outputs.bucket_name }}"
  region: "{{ .nuon.components.pulumi_s3.outputs.bucket_region }}"
"""
max_auto_retries = 5
