name           = "forgejo"
type           = "helm_chart"
chart_name     = "forgejo"
namespace      = "forgejo"
storage_driver = "configmap"
timeout        = "15m"
max_auto_retries = 5
dependencies   = ["img_forgejo", "forgejo_db_secret", "forgejo_cache_secret"]

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "forgejo-aws/src/helm/forgejo"
branch    = "main"

[[values_file]]
contents = "./values/forgejo/values.yaml"

[values]
image                = "{{ .nuon.components.img_forgejo.outputs.image.repository }}:{{ .nuon.components.img_forgejo.outputs.image.tag }}"
adminUser            = "{{ .nuon.inputs.inputs.forgejo_admin_user }}"
adminEmail           = "{{ .nuon.inputs.inputs.forgejo_admin_email }}"
repoStorageGB        = "{{ .nuon.inputs.inputs.repo_storage_gb }}"
siteDomain           = "{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}"
