name        = "deploy_all"
description = "Deploys all EKS components in order."
readme      = "./runbooks/deploy_all.md"

[[steps]]
name           = "Deploy certificate"
type           = "component_deploy"
component_name = "certificate"

[[steps]]
name           = "Deploy whoami"
type           = "component_deploy"
component_name = "whoami"

[[steps]]
name           = "Deploy ALB"
type           = "component_deploy"
component_name = "application_load_balancer"
