type = "deprovision"
name = "{{.nuon.install.id}}-alb-teardown"
description = "teardown the alb component."
display_name = "alb teardown role"
permissions_boundary = "./deprovision_boundary.json"

[[policies]]
name = "{{.nuon.install.id}}-alb-teardown"
contents = """
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "EKSAuth",
      "Effect": "Allow",
      "Action": [
        "eks:DescribeCluster"
      ],
      "Resource": "*"
    }
  ]
}
"""
