cloud: aws
category:
  - self-hosted
  - ai-ml
infra: ecs
stack:
  - terraform
  - container-image
features:
  - policies
  - byo
tags:
  - ecs
  - llm
  - openai
links:
  upstream: https://openwebui.com/
