# install

name = "customer-barclays-stage"
app_branch = "main"
approval_option = "approve-all"

[labels]
env     = "stage"
release = "{{ .nuon.install.inputs.sonarqube_build_number }}"

[aws_account]
region = "us-east-1"

[[inputs]]
sonarqube_build_number = "26.9.0.129388"
