# terraform

name              = "certificate"
type              = "terraform_module"
terraform_version = "1.11.3"
max_auto_retries = 5

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "eks-simple/src/components/certificate"
branch    = "main"

[vars]
install_id  = "{{ .nuon.install.id }}"
region      = "{{ .nuon.install_stack.outputs.region }}"
zone_id     = "{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.zone_id }}"
domain_name = "*.{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}"

[[operation_roles]]
operation = "deploy"
role      = "{{.nuon.install.id}}-certificate-deploy"

[[operation_roles]]
operation = "teardown"
role      = "{{.nuon.install.id}}-certificate-teardown"
