# policies

[[policy]]
type     = "sandbox"
engine   = "opa"
contents = "./policies/pass-vpc-cidr.rego"

[[policy]]
type     = "sandbox"
engine   = "opa"
contents = "./policies/pass-multi-az-subnets.rego"

[[policy]]
type       = "terraform_module"
engine     = "opa"
components = ["alb"]
contents   = "./policies/warn-alb-public-access.rego"
