#:schema https://api.nuon.co/v1/general/config-schema?type=install

name = "demo-2"
app_branch = "main"
approval_option = "approve-all"

[labels]
fleet = "true"
wave  = "default"

[aws_account]
region = "us-east-1"

[[inputs]]
instance_type  = "t3a.xlarge"
install_docker = "true"
