#:schema https://api.nuon.co/v1/general/config-schema?type=install

name = "full-stack-2"
approval_option = "approve-all"

[labels]
prod = "true"
tier = "full-stack"

[aws_account]
region = "us-east-1"
