#:schema https://api.nuon.co/v1/general/config-schema?type=install

name = "weekly-1"
app_branch = "weekly"
approval_option = "approve-all"

[labels]
fleet = "true"
wave  = "default"

[aws_account]
region = "us-east-1"

[[inputs]]
instance_type  = "t3a.medium"
install_docker = "false"
