# terraform
name              = "ec2"
type              = "terraform_module"
terraform_version = "1.11.4"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "httpbin/src/components/ec2"
branch    = "main"

[vars]
install_id         = "{{.nuon.install.id}}"
region             = "{{.nuon.sandbox.outputs.account.region}}"
subnet_id          = "{{index .nuon.sandbox.outputs.vpc.public_subnet_ids 0}}"
vpc_id             = "{{.nuon.sandbox.outputs.vpc.id}}"
instance_type      = "{{.nuon.inputs.inputs.instance_type}}"
http_port          = "{{.nuon.inputs.inputs.http_port}}"
httpbin_version    = "{{.nuon.inputs.inputs.httpbin_version}}"
allowed_ips        = "{{.nuon.inputs.inputs.allowed_ips}}"
max_response_size  = "{{.nuon.inputs.inputs.max_response_size}}"
max_duration       = "{{.nuon.inputs.inputs.max_duration}}"
log_level          = "{{.nuon.inputs.inputs.log_level}}"
