#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "ec2"
type              = "terraform_module"
terraform_version = "1.11.4"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "httpbin/src/components/ec2"
branch    = "main"

[vars]
install_id = "{{.nuon.install.id}}"
region     = "{{.nuon.sandbox.outputs.account.region}}"
subnet_id  = "{{index .nuon.sandbox.outputs.vpc.public_subnet_ids 0}}"
vpc_id     = "{{.nuon.sandbox.outputs.vpc.id}}"
