# terraform
name              = "dummy"
type              = "terraform_module"
terraform_version = "1.11.4"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "httpbin/src/components/dummy"
branch    = "test/httpbin-second-component"

[vars]
install_id = "{{.nuon.install.id}}"
