#:schema https://api.nuon.co/v1/general/config-schema?type=install
name = 'Dropbox'

[aws_account]
region = 'us-east-1'

# input.group :
[[inputs]]
block_direct = 'false'
cluster_version = '1.34'
coder_db_instance_type = 'db.t4g.micro'
max_token_lifetime = '8760h0m0s'
provisioners = '3'
release = 'v2.31.1'
replicas = '1'
session_duration = '168h0m0s'
telemetry = 'true'
