#:schema https://api.nuon.co/v1/general/config-schema?type=install

# Preview install for nuon branches preview (apply). Omit app_branch so a
# branches trigger on main does not also deploy here.
name = "preview"
approval_option = "approve-all"

[labels]
preview = "true"
channel = "mainline"
release = "{{ .nuon.install.inputs.coder_image_tag }}"

[aws_account]
region = "us-east-1"

[[inputs]]
coder_image_tag = "v2.36.3"
