# pulumi
name    = "pulumi_gcs_bucket"
type    = "pulumi"
runtime = "go"
max_auto_retries = 5

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "gcp-cloud-run/src/components/pulumi-gcs-bucket"
branch    = "main"

[config]
"gcp:project" = "{{.nuon.install_stack.outputs.project_id}}"
"gcp:region"  = "{{.nuon.inputs.inputs.region}}"

[env_vars]
INSTALL_ID = "{{.nuon.install.id}}"
