cloud: aws
category:
  - self-hosted
  - monitoring
infra: eks
stack:
  - terraform
  - helm
  - manifest
features:
  - actions
  - policies
  - secrets
tags:
  - eks
  - kubernetes
  - helm
  - monitoring
  - observability
  - prometheus
  - postgresql
links:
  blog: https://nuon.co/blog/installing-grafana-with-nuon/
  upstream: https://grafana.com
