[[policy]]
type     = "kubernetes_cluster"
contents = "./policies/disallow-ingress-nginx-custom-snippets.yaml"

[[policy]]
type     = "sandbox"
engine   = "opa"
contents = "./policies/warn-public-eks-endpoint.rego"
