name         = "forgejo_cache_secret"
type         = "kubernetes_manifest"
dependencies = ["pulumi_redis"]
namespace    = "forgejo"

manifest = """
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-cache
  namespace: forgejo
type: Opaque
stringData:
  host: "{{ .nuon.components.pulumi_redis.outputs.host }}"
  port: "{{ .nuon.components.pulumi_redis.outputs.port }}"
"""
max_auto_retries = 5
