name         = "forgejo_s3_secret"
type         = "kubernetes_manifest"
dependencies = ["pulumi_storage"]
namespace    = "forgejo"

manifest = """
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-s3
  namespace: forgejo
type: Opaque
stringData:
  bucket: "{{ .nuon.components.pulumi_storage.outputs.bucket_name }}"
  region: "{{ .nuon.components.pulumi_storage.outputs.bucket_region }}"
  access_id: "{{ .nuon.components.pulumi_storage.outputs.hmac_access_id }}"
  access_secret: "{{ .nuon.components.pulumi_storage.outputs.hmac_secret }}"
"""
max_auto_retries = 5
