# action
name    = "sonar_admin_secret"
timeout = "1m"
enable_kube_config = true
labels  = { service = "sonarqube", type = "lifecycle" }

[[triggers]]
type           = "post-deploy-component"
component_name = "rds_cluster_sonar"

[[triggers]]
type = "manual"

[[steps]]
name    = "Ensure admin password secret keys"
command = "./admin_secret/ensure.sh"

[steps.public_repo]
repo      = "nuonco/example-app-configs"
directory = "sonar/sonar-aws/src/actions"
branch    = "mm/sonar"

[steps.env_vars]
TARGET_NAME      = "sonar-admin-password"
TARGET_NAMESPACE = "sonarqube"
