name = "tailscale_oauth_client_secret"
display_name = "Tailscale: OAuth Client Secret"
description = "Tailscale OAuth Client Secret for tailscale operator"
required = false

[[kubernetes_sync_targets]]
namespaces = ["tailscale"]
name = "operator-oauth"
key = "client_secret"
