# action
name               = "langfuse_secrets"
timeout            = "1m"
enable_kube_config = true

[[triggers]]
type           = "pre-deploy-component"
component_name = "langfuse"

[[triggers]]
type = "manual"

[[steps]]
name    = "Generate Langfuse application secrets"
command = "./generate.sh"

[steps.public_repo]
repo      = "nuonco/example-app-configs"
directory = "langfuse/src/actions/langfuse_secrets"
branch    = "mm/langfuse"

[steps.env_vars]
TARGET_NAMESPACE = "langfuse"
INSTALL_ID       = "{{ .nuon.install.id }}"
