# kubernetes-manifest

name      = "maintenance_rbac"
type      = "kubernetes_manifest"
namespace = "whoami"

manifest = """
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maintenance
  namespace: whoami
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["bind", "create", "delete", "escalate", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "serviceaccounts"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maintenance
  namespace: whoami
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: maintenance
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: maintenance
"""

[[operation_roles]]
operation = "deploy"
role      = "{{.nuon.install.id}}-provision"

[[operation_roles]]
operation = "teardown"
role      = "{{.nuon.install.id}}-provision"
