apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: "{{ $.Values.deployment.namespace }}"
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: ".25"
              memory: "128Mi"
            requests:
              cpu: ".1"
              memory: "64Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
