apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  namespace: "{{ $.Values.deployment.namespace }}"
spec:
  rules:
    - host: httpbin.inlloc439c7nwaddbbc3oduuk0.nuon.run
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 80
  ingressClassName: nginx
