runner_type = "gcp"
helm_driver = "configmap"
init_script_url = "https://raw.githubusercontent.com/nuonco/runner/main/scripts/gcp/init-mng-v2.sh"
runner_api_url  = "https://runner-api-proxy.prod.nuon.co"
public_api_url  = "https://runner-api-proxy.prod.nuon.co"
