name         = "admin_password"
display_name = "Admin Password"
description  = "Password for accessing the admin panel to manage monitoring settings"
default      = "demo-admin-pass-2024"

user_configurable = true