#:schema https://api.nuon.co/v1/general/config-schema?type=install

# Lab preview install for app branch main [preview] → preview-main.
name = "preview-main"
app_branch = "main"
approval_option = "approve-all"

[labels]
channel = "mainline"
release = "{{ .nuon.install.inputs.coder_image_tag }}"
fleet   = "true"
wave    = "preview"

[aws_account]
region = "us-east-1"

[[inputs]]
coder_image_tag = "v2.36.3"
