# https://github.com/christianhuth/helm-charts/blob/main/charts/baserow/values.yaml
# https://hub.docker.com/r/baserow/baserow/tags

frontend:
  image:
    tag: "{{.nuon.inputs.inputs.baserow_release}}"

  ingress:
    enabled: false

backend:
  asgi:
    image:
      tag: "{{.nuon.inputs.inputs.baserow_release}}"

celery:
  image:
    tag: "{{.nuon.inputs.inputs.baserow_release}}"

config:
  airtableImportSoftTimeLimit: "1800"
  hoursUntilTrashPermanentlyDeleted: "24"
  initialCreateSyncTableDataLimit: "5000"
  logging:
    backendDebug: "off"
    # -- The default log level used by the backend, supports ERROR, WARNING, INFO, DEBUG, TRACE
    backendLogLevel: "INFO"
    databaseLogLevel: "ERROR"
  tokens:
    # -- The number of minutes which specifies how long access tokens are valid. This will be converted in a timedelta value and added to the current UTC time during token generation to obtain the token’s default “exp” claim value.
    accessTokenLifetimeMinutes: "10"
    # -- The number of hours which specifies how long refresh tokens are valid. This will be converted in a timedelta value and added to the current UTC time during token generation to obtain the token’s default “exp” claim value.
    refreshTokenLifetimeHours: "168"

persistence:
  # -- use a PVC to persist file uploads
  enabled: true
  # -- the desired access modes the volume should have.
  accessModes:
    - ReadWriteOnce
  # -- Annotations to be added to the PersistentVolumeClaim
  annotations: {}
  # -- provide an existing PersistentVolumeClaim
  existingClaim: ""
  # -- Name of the StorageClass required by the claim.
  storageClassName: "gp2"
  # -- Storage size for file uploads
  size: "20Gi"

wsgi:
  image:
    tag: "{{.nuon.inputs.inputs.baserow_release}}"

  ingress:
    enabled: false

# General configuration shared between the frontend and backend
config:
  # -- The publicly accessible URL of the backend. Should include the port if non-standard.
  publicBackendUrl: "http://localhost:8000"
  # -- The publicly accessible URL of the frontend. Should include the port if non-standard.
  publicFrontendUrl: "https://{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"

postgresql:
  enabled: true
  auth:
    database: baserow
    username: baserow
    password: baserow

redis:
  enabled: true
  auth:
    enabled: true
    password: baserow