# https://github.com/christianhuth/helm-charts/blob/main/charts/baserow/values.yaml
# https://hub.docker.com/r/baserow/baserow/tags

frontend:
  image:
    #repository: baserow/baserow
    repository: "baserow/web-frontend"
    tag: "{{.nuon.inputs.inputs.baserow_release}}"

  ingress:
    enabled: false

  livenessProbe:
    # -- Initial delay seconds for livenessProbe
    initialDelaySeconds: 600
    # -- Period seconds for livenessProbe
    periodSeconds: 30
    # -- Success threshold for livenessProbe
    successThreshold: 1

  readinessProbe:
    # -- Initial delay seconds for readinessProbe
    initialDelaySeconds: 600
    # -- Period seconds for readinessProbe
    periodSeconds: 30
    # -- Success threshold for readinessProbe
    successThreshold: 1

  extraEnv:
    - name: NUXT_PUBLIC_FRONTEND_URL
      value: "https://{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"    
    - name: NUXT_PUBLIC_BACKEND_URL
      value: "https://api.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"

  extraEnv:
    - name: BASEROW_EXTRA_ALLOWED_HOSTS
      value: "api.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}},{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"


backend:
  asgi:
    image:
      tag: "{{.nuon.inputs.inputs.baserow_release}}"

    extraEnv:
      - name: BASEROW_EXTRA_ALLOWED_HOSTS
        value: "api.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}},{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}},baserow-wsgi.baserow.svc.cluster.local" 

  celery:
    image:
      tag: "{{.nuon.inputs.inputs.baserow_release}}"

  wsgi:
    image:
      tag: "{{.nuon.inputs.inputs.baserow_release}}"

    extraEnv:
      - name: BASEROW_EXTRA_ALLOWED_HOSTS
        value: "api.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}},{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}},baserow-wsgi.baserow.svc.cluster.local"      

    ingress:
      enabled: false 


config:
  # -- The publicly accessible URL of the backend. Should include the port if non-standard.
  publicBackendUrl: "https://api.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"
  #publicBackendUrl: "http://localhost:8000"
  # -- The publicly accessible URL of the frontend. Should include the port if non-standard.
  publicFrontendUrl: "https://{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"

persistence:
  # -- use a PVC to persist file uploads
  enabled: true
  # -- the desired access modes the volume should have.
  accessModes:
    - ReadWriteOnce
  # -- Annotations to be added to the PersistentVolumeClaim
  annotations: {}
  # -- provide an existing PersistentVolumeClaim
  existingClaim: ""
  # -- Name of the StorageClass required by the claim.
  storageClassName: "gp2"
  # -- Storage size for file uploads
  size: "20Gi"

postgresql:
  enabled: true
  auth:
    database: baserow
    username: baserow
    password: baserow

redis:
  enabled: true
  auth:
    enabled: true
    password: baserow
