# https://github.com/christianhuth/helm-charts/blob/main/charts/baserow/values.yaml
# https://hub.docker.com/r/baserow/baserow/tags

frontend:
  image:
    repository: "baserow/web-frontend"
    tag: "{{.nuon.inputs.inputs.baserow_release}}"

  ingress:
    enabled: false

  readinessProbe:
    initialDelaySeconds: 30  
    periodSeconds: 30
    timeoutSeconds: 10       
    successThreshold: 1
    failureThreshold: 5
  
  livenessProbe:
    initialDelaySeconds: 60  
    periodSeconds: 30
    timeoutSeconds: 10       
    successThreshold: 1
    failureThreshold: 5

  resources:
    requests:
      memory: "1Gi"      
      cpu: "500m"      
    limits:
      memory: "2Gi"     
      cpu: "1500m"      

  extraEnv:
    - name: BASEROW_EXTRA_ALLOWED_HOSTS
      value: "*" 

backend:
  asgi:
    image:
      tag: "{{.nuon.inputs.inputs.baserow_release}}"

    extraEnv:
      - name: BASEROW_EXTRA_ALLOWED_HOSTS
        value: "*"

  celery:
    image:
      tag: "{{.nuon.inputs.inputs.baserow_release}}"

    resources:
      requests:
        memory: "1Gi"      
        cpu: "500m"      
      limits:
        memory: "2Gi"     
        cpu: "1500m" 

  wsgi:
    image:
      tag: "{{.nuon.inputs.inputs.baserow_release}}"

    extraEnv:
      - name: BASEROW_EXTRA_ALLOWED_HOSTS
        value: "*"     

    ingress:
      enabled: false 

  config:
    aws:
      # -- Name of existing secret to use for AWS credentials like Access Key Id and Secret Access Key. Keys in secret should be called `access-key-id` and `secret-access-key`.
      existingSecret: "aws-credentials"
      bucketName: "baserow-files-nuon"
      s3RegionName: "us-west-2"


config:
  # -- The publicly accessible URL of the backend. Should include the port if non-standard.
  publicBackendUrl: "https://api.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"
  # -- The publicly accessible URL of the frontend. Should include the port if non-standard.
  publicFrontendUrl: "https://{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"

persistence:
  # -- use a PVC to persist file uploads
  enabled: true
  # -- the desired access modes the volume should have.
  accessModes:
    - ReadWriteOnce
  # -- Annotations to be added to the PersistentVolumeClaim
  annotations: {}
  # -- provide an existing PersistentVolumeClaim
  existingClaim: ""
  # -- Name of the StorageClass required by the claim.
  storageClassName: "gp2"
  # -- Storage size for file uploads
  size: "20Gi"

postgresql:
  enabled: true
  auth:
    database: baserow
    username: baserow
    password: baserow

redis:
  enabled: true
  auth:
    enabled: true
    password: baserow
