name        = "deploy_verify_and_restart"
description = "Deploys all components, runs verification checks, then restarts the service."
readme      = "./runbooks/deploy_verify_and_restart.md"

[[steps]]
name           = "Deploy container image"
type           = "component_deploy"
component_name = "img_whoami"

[[steps]]
name           = "Deploy ECS cluster"
type           = "component_deploy"
component_name = "cluster"

[[steps]]
name           = "Deploy certificate"
type           = "component_deploy"
component_name = "certificate"

[[steps]]
name           = "Deploy ECS service"
type           = "component_deploy"
component_name = "whoami"

[[steps]]
name           = "Deploy ALB"
type           = "component_deploy"
component_name = "alb"

[[steps]]
name        = "Service status"
type        = "action"
action_name = "service_status"

[[steps]]
name        = "Certificate status"
type        = "action"
action_name = "certificate_status"

[[steps]]
name        = "Curl endpoint"
type        = "action"
action_name = "curl_endpoint"

[[steps]]
name        = "Restart service"
type        = "action"
action_name = "restart_service"
