name        = "deploy_and_verify"
description = "Deploys all components, then runs verification checks."
readme      = "./runbooks/deploy_and_verify.md"

[labels]
service = "ecs"
type    = "deployment"

[[steps]]
name           = "Deploy container image"
type           = "component_deploy"
component_name = "img_whoami"

[[steps]]
name           = "Deploy ECS cluster"
type           = "component_deploy"
component_name = "cluster"

[[steps]]
name           = "Deploy certificate"
type           = "component_deploy"
component_name = "certificate"

[[steps]]
name           = "Deploy ECS service"
type           = "component_deploy"
component_name = "whoami"

[[steps]]
name           = "Deploy ALB"
type           = "component_deploy"
component_name = "alb"

[[steps]]
name        = "Service status"
type        = "action"
action_name = "service_status"

[[steps]]
name        = "Certificate status"
type        = "action"
action_name = "certificate_status"

[[steps]]
name        = "Curl endpoint"
type        = "action"
action_name = "curl_endpoint"
