name        = "deploy_all"
description = "Deploys all ECS components in order."
readme      = "./runbooks/deploy_all.md"

[labels]
service = "ecs"
type    = "deployment"

[[steps]]
name           = "Deploy container image"
type           = "component_deploy"
component_name = "img_whoami"

[[steps]]
name           = "Deploy ECS cluster"
type           = "component_deploy"
component_name = "cluster"

[[steps]]
name           = "Deploy certificate"
type           = "component_deploy"
component_name = "certificate"

[[steps]]
name           = "Deploy ECS service"
type           = "component_deploy"
component_name = "whoami"

[[steps]]
name           = "Deploy ALB"
type           = "component_deploy"
component_name = "alb"
