name = "img_event_proof"
type = "container_image"

[gcp_gar]
gcp_project_id = "nuon-gcp-support"
region         = "us-west1"
image_url      = "us-west1-docker.pkg.dev/nuon-gcp-support/nuon-event-proof/clickhouse-server"
update_policy  = "^1.0.0"
