type    = "pulumi"
runtime = "go"

[public_repo]
directory = "."
repo      = "nuonco/gcp-gke-sandbox-pulumi"
branch    = "main"

# nuon_id, project_id, region, network and subnetwork are injected automatically
# for GCP runners; only app-specific config is set here.
[pulumi_config]
"nuon:cluster_name"         = "n-{{ .nuon.install.id }}"
"nuon:enable_nuon_dns"      = "true"
"nuon:public_root_domain"   = "{{ .nuon.install.id }}.{{ .nuon.inputs.inputs.domain }}"
"nuon:internal_root_domain" = "internal.{{ .nuon.install.id }}.{{ .nuon.inputs.inputs.domain }}"
