AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for the install

Parameters:
  NuonInstallID:
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref NuonInstallID

Outputs:
  BucketName:
    Value: !Ref Bucket
  BucketArn:
    Value: !GetAtt Bucket.Arn
