name           = "secrets_demo"
type           = "helm_chart"
chart_name     = "secrets-demo"
namespace      = "secrets-demo"
storage_driver = "configmap"
max_auto_retries = 5

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "gke-secrets/src/components/secrets-demo"
branch    = "am/conf-updates"

[[values_file]]
contents = "./values/secrets-demo.yaml"
