#:schema https://api.nuon.co/v1/general/config-schema?type=install

name = "customer-dropbox-stage"
app_branch = "main"
approval_option = "approve-all"

[labels]
channel = "mainline"
env     = "stage"
release = "{{ .nuon.install.inputs.coder_image_tag }}"

[aws_account]
region = "us-east-1"

[[inputs]]
coder_image_tag = "v2.36.3"
