name         = "api_key_secret"
display_name = "API Key Secret"
description  = "Syncs the api_key input value into a Kubernetes secret."
input_name   = "api_key"

kubernetes_sync             = true
kubernetes_secret_namespace = "secrets-demo"
kubernetes_secret_name      = "api-key-secret"

user_configurable = true
