name = "dev"

[connected_repo]
repo = "nuonco/example-app-configs"
directory = "aca-medium"
branch = "fd/feat/aca-medium"

[[install_groups]]
name = "dev"
order = 0

[install_groups.label_selector]
dev = "true"
