cloud: aws
category:
  - ai-ml
  - databases
infra: eks
stack:
  - terraform
  - helm
  - manifest
  - container-image
features:
  - actions
  - policies
tags:
  - eks
  - kubernetes
  - rds
  - clickhouse
  - datadog
  - temporal
  - ai
  - llm
  - karpenter
links:
  temporal: https://github.com/temporalio/helm-charts
  temporal-ai-agent: https://github.com/temporal-community/temporal-ai-agent/
