#:schema https://api.nuon.co/v1/general/config-schema?source=kubernetes-manifest
  name = "mattermost_service_account"
  type = "kubernetes_manifest"
  dependencies = ["s3_buckets"]
  namespace = "mattermost"

  manifest = """
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: mattermost
    annotations:
      eks.amazonaws.com/role-arn: "{{.nuon.components.s3_buckets.outputs.mattermost_bucket_role.arn}}"
  """