#:schema https://api.nuon.co/v1/general/config-schema?sourcekubernetes-manifest

name   = "mattermost_manifest_db_secret"
type   = "kubernetes_manifest"
dependencies   = ["postgres_db"]


namespace = "mattermost"
manifest = """
apiVersion: v1
kind: Secret
metadata:
  name: mm-postgres-connection
type: Opaque
stringData:
  DB_CONNECTION_STRING: "postgres://mattermost:mattermost@postgresql.mattermost.svc.cluster.local:5432/mattermost?sslmode=disable&connect_timeout=10"
  DB_CONNECTION_CHECK_URL: "postgres://mattermost:mattermost@postgresql.mattermost.svc.cluster.local:5432/postgres?connect_timeout=10"
"""