#:schema https://api.nuon.co/v1/general/config-schema?type=kubernetes-manifest

  name = "mattermost_s3_secret"
  type = "kubernetes_manifest"
  dependencies = ["s3_buckets"]

  namespace = "mattermost"
  manifest = """
  apiVersion: v1
  kind: Secret
  metadata:
    name: mattermost-s3-secret
    namespace: mattermost
  type: Opaque
  stringData:
    accesskey: ""
    secretkey: ""
  """