#:schema https://api.nuon.co/v1/general/config-schema?sourcekubernetes-manifest

name   = "mattermost_manifest_installation"
type   = "kubernetes_manifest"
dependencies   = ["postgres_db","mattermost_manifest_db_secret","s3_buckets"]

namespace = "mattermost"
manifest = """
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mm
  namespace: mattermost
spec:
  image: mattermost/mattermost-enterprise-edition
  version: "{{.nuon.inputs.inputs.app_release}}"
  useServiceLoadBalancer: false 
  ingress:
    enabled: false
  serviceAccountName: mm
  podExtensions:
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: "{{.nuon.components.s3_buckets.outputs.mattermost_bucket_role.arn}}"
  database:
    external:
      secret: mm-postgres-connection
  fileStore:
    external:
      url: s3.amazonaws.com
      bucket: "{{.nuon.components.s3_buckets.outputs.mattermost_bucket.id}}"
      secret: "mattermost-s3-secret"
  mattermostEnv:
    - name: MM_SERVICESETTINGS_SITEURL
      value: "https://{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"         
    """

# https://github.com/mattermost/mattermost-operator/blob/master/docs/examples/mattermost_full.yaml
# https://github.com/mattermost/mattermost-operator/blob/master/config/crd/bases/installation.mattermost.com_mattermosts.yaml
# https://github.com/mattermost/mattermost/releases/