name         = "application_load_balancer"
type         = "helm_chart"
chart_name   = "application-load-balancer"
dependencies = ["mattermost_manifest_installation","certificate"]

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "mattermost/src/components/alb"
branch    = "mm/mattermost"

[values]
domain_certificate = "{{.nuon.components.certificate.outputs.public_domain_certificate_arn}}"
domain             = "{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"

https_port         = "443"
service_name       = "mm-web"
service_port       = "8065"
install_name       = "{{.nuon.install.id}}"
namespace          = "mattermost"
healthcheck_path   = "/"
