cloud: aws
category:
  - self-hosted
infra: eks
stack:
  - terraform
  - helm
  - manifest
features:
  - actions
  - policies
  - secrets
tags:
  - eks
  - kubernetes
  - helm
  - collaboration
  - operator
links:
  blog: https://nuon.co/blog/installing-mattermost-with-nuon/
  upstream: https://mattermost.com
