#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "mattermost"
description  = "Environment variables and configurations for the Mattermost operator and app. Operator: https://github.com/mattermost/mattermost-operator/releases App: https://github.com/mattermost/mattermost/releases/"
display_name = "Application Configurations"

[[input]]
name         = "operator_release"
description  = "The release of the Mattermost operator to deploy. "
default      = "v1.24.0"
display_name = "Operator Release"
group        = "mattermost"

[[input]]
name         = "app_release"
description  = "The release of the Mattermost operator to deploy. Note: Remove the 'v' prefix, e.g., use 10.11.2 not v10.11.2"
default      = "10.11.2"
display_name = "Mattermost App Release"
group        = "mattermost"

[[input]]
name         = "replicas"
description  = "The number of replicas of the Mattermost control plane pods to deploy"
default      = "1"
display_name = "Mattermost Replicas"
group        = "mattermost"

[[group]]
name         = "compute"
description  = "How many nodes to provision to support dev environments? https://aws.amazon.com/ec2/instance-types/ e.g., t3-medium, t3.xlarge, t3.2xlarge"
display_name = "Kubernetes Nodes"
group        = "compute"

[[input]]
name         = "instance_size"
description  = "The AWS instance size to use for each node in the EKS cluster"
default      = "t3-medium"
display_name = "Node Instance Size"
group        = "compute"

[[input]]
name         = "min_size"
description  = "Minimum number of nodes to provision in the EKS cluster"
default      = "3"
display_name = "Minimum Node Count"
group        = "compute"

[[input]]
name         = "max_size"
description  = "Maximum number of nodes to provision in the EKS cluster"
default      = "5"
display_name = "Maximum Node Count"
group        = "compute"

[[input]]
name         = "desired_capacity"
description  = "Desired number of nodes to provision in the EKS cluster"
default      = "3"
display_name = "Desired Node Count"
group        = "compute"
