version = "v2"

display_name = "Mattermost"
description  = "Secure messaging & collaboration tool on AWS EKS"
readme       = "./README.md"

[onboarding]
enabled        = true
category       = "self-hosted"
difficulty     = "medium"
cloud_provider = "aws"
