apiVersion: v1
kind: Service
metadata:
  name: secrets-demo
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: secrets-demo
  ports:
    - port: 80
      targetPort: 80
