#:schema https://api.nuon.co/v1/general/config-schema?type=kubernetes-manifest

name = "twenty_pv_db"
type = "kubernetes_manifest"
dependencies = []

namespace = "twentycrm"
manifest = """
apiVersion: v1
kind: PersistentVolume
metadata:
  name: twentycrm-db-pv
  namespace: twentycrm
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/data/twentycrm/db
  persistentVolumeReclaimPolicy: Retain
"""