#:schema https://api.nuon.co/v1/general/config-schema?type=kubernetes-manifest

name = "twenty_deployment_server"
type = "kubernetes_manifest"
dependencies = ["twenty_pvc_server", "twenty_pvc_docker_data", "twenty_deployment_db", "twenty_deployment_redis", "twenty_secret"]

namespace = "twentycrm"
manifest = """
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twentycrm-server
  name: twentycrm-server
  namespace: twentycrm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: twentycrm-server
  template:
    metadata:
      labels:
        app: twentycrm-server
    spec:
      volumes:
      - name: twentycrm-server-data
        persistentVolumeClaim:
          claimName: twentycrm-server-pvc
      - name: twentycrm-docker-data
        persistentVolumeClaim:
          claimName: twentycrm-docker-data-pvc
      containers:
      - name: twentycrm
        image: twentycrm/twenty:{{ .nuon.inputs.inputs.twenty_release }}
        imagePullPolicy: Always
        env:
        - name: NODE_PORT
          value: "3000"
        - name: SERVER_URL
          value: "https://{{ .nuon.install.sandbox.outputs.nuon_dns.public_domain.name }}:443"
        - name: "PG_DATABASE_URL"
          value: "postgres://{{ .nuon.inputs.inputs.postgres_user }}:{{ .nuon.inputs.inputs.postgres_password }}@twentycrm-db.twentycrm.svc.cluster.local/default"
        - name: "REDIS_URL"
          value: "redis://twentycrm-redis.twentycrm.svc.cluster.local:6379"
        - name: SIGN_IN_PREFILLED
          value: "false"
        - name: STORAGE_TYPE
          value: "local"
        - name: "ACCESS_TOKEN_EXPIRES_IN"
          value: "7d"
        - name: "LOGIN_TOKEN_EXPIRES_IN"
          value: "1h"
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: tokens
              key: appSecret
        - name: "ACCESS_TOKEN_SECRET"
          valueFrom:
            secretKeyRef:
              name: tokens
              key: accessToken
        - name: "LOGIN_TOKEN_SECRET"
          valueFrom:
            secretKeyRef:
              name: tokens
              key: loginToken
        - name: "REFRESH_TOKEN_SECRET"
          valueFrom:
            secretKeyRef:
              name: tokens
              key: refreshToken
        - name: "FILE_TOKEN_SECRET"
          valueFrom:
            secretKeyRef:
              name: tokens
              key: fileToken
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        volumeMounts:
        - mountPath: /app/packages/twenty-server/.local-storage
          name: twentycrm-server-data
        - mountPath: /app/docker-data
          name: twentycrm-docker-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
"""