#:schema https://api.nuon.co/v1/general/config-schema?type=helm
name         = "application_load_balancer"
type         = "helm_chart"
chart_name   = "application-load-balancer"
dependencies = ["certificate", "twenty_deployment_server"]

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "twenty/src/components/alb"
branch    = "mm/twenty"

[values]
domain_certificate = "{{.nuon.components.certificate.outputs.public_domain_certificate_arn}}"
domain             = "{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"

https_port         = "443"
service_name       = "twentycrm-server"
service_port       = "3000"
install_name       = "{{.nuon.install.id}}"
namespace          = "twentycrm"
healthcheck_path   = "/healthz"
