cloud: aws
category:
  - self-hosted
  - databases
infra: eks
stack:
  - helm
  - manifest
  - container-image
features:
  - actions
  - policies
tags:
  - eks
  - kubernetes
  - clickhouse
  - database
  - analytics
  - operator
  - karpenter
  - tailscale
  - vpn
links:
  upstream: https://clickhouse.com
  tailscale: https://tailscale.com
