version = "v2"

display_name = "Clickhouse + Tailscale"
description  = "Clickhouse on EKS with Tailscale for private ingress via tailnet"
readme       = "./README.md"

[onboarding]
enabled        = true
category       = "self-hosted"
difficulty     = "medium"
cloud_provider = "aws"
