# action
name    = "compute_get_deployments"
timeout = "15s"

enable_kube_config = true
kubernetes_context = "compute"

[[triggers]]
type = "manual"

[[steps]]
name            = "exec"
inline_contents = "./src/kubectl/deployments.sh"
