cloud: aws
category:
  - architecture
infra: eks
stack:
  - terraform
  - helm
  - manifest
features:
  - actions
  - policies
  - secrets
tags:
  - eks
  - kubernetes
  - karpenter
  - ebs
  - image-cache
  - gvisor
  - sandboxing
  - security
links: {}
