type        = "aws-cloudformation"
name        = "nuon-eks-karpenter-image-cache-{{.nuon.install.id}}"
description = "QuickLink to install runner: Install {{.nuon.install.id}}"

# nested stack
vpc_nested_template_url    = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.4.0/vpc/eks/default/stack.yaml"
runner_nested_template_url = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/aws-cloudformation-templates/v0.4.0/runner/asg/stack.yaml"
