name              = "api_key"
description       = "API key provided by the install operator"
display_name      = "API Key"
group             = "credentials"
sensitive         = true
user_configurable = true
