# action
name               = "dragonfly_secrets"
timeout            = "1m"
enable_kube_config = true

[[triggers]]
type           = "pre-deploy-component"
component_name = "dragonfly_instance"

[[triggers]]
type = "manual"

[[steps]]
name    = "Generate Dragonfly AUTH password"
command = "./generate.sh"

[steps.public_repo]
repo      = "nuonco/example-app-configs"
directory = "dragonfly/src/actions/dragonfly_secrets"
branch    = "mm/dragonfly"

[steps.env_vars]
TARGET_NAMESPACE = "dragonfly"
AUTH_ENABLED     = "{{ .nuon.inputs.inputs.auth_enabled }}"
