# action
name               = "trigger_snapshot"
timeout            = "5m"
enable_kube_config = true

[[triggers]]
type = "manual"

[[steps]]
name    = "redis-cli SAVE"
command = "./trigger.sh"

[steps.public_repo]
repo      = "nuonco/example-app-configs"
directory = "dragonfly/src/actions/trigger_snapshot"
branch    = "mm/dragonfly"

[steps.env_vars]
TARGET_NAMESPACE = "dragonfly"
AUTH_ENABLED     = "{{ .nuon.inputs.inputs.auth_enabled }}"
BUCKET_NAME      = "{{ .nuon.components.dragonfly_s3_bucket.outputs.bucket_name }}"
AWS_REGION       = "{{ .nuon.components.dragonfly_s3_bucket.outputs.region }}"
