name              = "service_account"
type              = "terraform_module"
terraform_version = "1.11.3"
max_auto_retries = 5

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "gke-workload-identity/src/components/service-account"
branch    = "main"

[vars]
project_id = "{{ .nuon.install_stack.outputs.project_id }}"
install_id = "{{ .nuon.install.id }}"
namespace  = "wi-demo"
