cloud: aws
category:
  - self-hosted
infra: eks
stack:
  - terraform
  - helm
features:
  - actions
  - policies
  - secrets
tags:
  - eks
  - kubernetes
  - postgresql
  - dev-environments
  - cde
links:
  blog: https://nuon.co/blog/installing-coder-with-nuon/
  upstream: https://coder.com
