# policies

[[policy]]
type     = "kubernetes_cluster"
contents = "./disallow-ingress-nginx-custom-snippets.yaml"

[[policy]]
type     = "sandbox"
engine   = "opa"
contents = "./warn-public-eks-endpoint.rego"
