#:schema https://api.nuon.co/v1/general/config-schema?type=terraform_module
name              = "image_cache"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "nuonco/example-app-configs"
directory = "eks-karpenter-image-cache/src/components/image_cache"
branch    = "am/eks-kap-img-cache"

[vars]
region             = "{{.nuon.install_stack.outputs.region}}"
vpc_id             = "{{.nuon.install.sandbox.outputs.vpc.id}}"
subnet_id          = "{{.nuon.install.sandbox.outputs.vpc.runner_subnet_id}}"
kubernetes_version = "{{.nuon.install.sandbox.outputs.cluster.version}}"
volume_size_gb     = "50"
instance_type      = "m5.xlarge"
images             = '["traefik/whoami:v1.10.3", "nginx:1.27.4", "grafana/grafana:11.6.0", "redis:7.4.2"]'
