#:schema https://api.nuon.co/v1/general/config-schema?type=kubernetes_manifest
name         = "node_class"
type         = "kubernetes_manifest"
namespace    = "kube-system"
dependencies = ["image_cache"]

manifest = "./manifests/ec2nodeclass.yaml"
max_auto_retries = 5
