name = "tailscale_oauth_client_id"
display_name = "Tailscale: OAuth Client ID"
description = "Tailscale OAuth Client ID for tailscale operator"
required = false

[[kubernetes_sync_targets]]
namespaces = ["tailscale"]
name = "operator-oauth"
key = "client_id"
